### ISSUE TITLE
@font-face woff?

### ISSUE THREAD

**Issue by T35R6braPwgDJKq** [html-screen-capture-js/html-screen-capture-js#48]
```css
@font-face {
font-family: 'PFn';
src: url('data/1234.woff');
}
```
The fonts are not stored? or is that a local problem?
